//------------------------------------------------------------------------
// Copyright(c) 2024 HonoursProject.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"SingleStagePhaser.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"SingleStagePhaser VST3 (64Bit)"
#else
#define stringFileDescription	"SingleStagePhaser VST3"
#endif
#define stringCompanyName		"HonoursProject\0"
#define stringLegalCopyright	"Copyright(c) 2024 HonoursProject."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
